### ISSUE TITLE
Boxzilla showing page content instead of box content since latest update

### ISSUE THREAD

**Issue by arnelap** [ibericode/boxzilla-wp#130] opened 2018-05-31 06:13 UTC
Some users reported this issue. I've not been able to reproduce the issue myself.

https://secure.helpscout.net/conversation/590881438/14310?folderId=491452

**Comment by dannyvankooten** [comment] 2018-05-31 07:48
This is caused by themes or other plugins incorrectly using `the_content` filter without checking what it is they are modifying. Probably easier if we took the "safe approach" here, so reverted the change that enabled the use of stuff like Jetpack Photon etc..


Fixed in 50505978dc0176ad7c503193f92028c563b47265

**Closed by dannyvankooten** 2018-05-31 07:48 UTC
Labels: bug
